### PR TITLE
Reporting of Operation Life

### PR DESCRIPTION
**Pull request by HauHe**
This PR allows to report the IAMC variable `Lifetime` using the OSeMOSYS parameter `OperationalLife`. The Operational Life is reported for each year in the Modelling period.

The PR addresses #36

### CODE REVIEW

**Comment by willu47** [comment]
Hi @HauHe - the checks are failing due to the "linting".  Linting checks the formatting of the code is correct.  You need to install the pre-commit checks to pass these checks.  The easy way to do this is to use tox:

```bash
pip install tox
tox -e lint
```

**Comment by HauHe** [comment]
Hm, used lint and it changed some dashes from single to double. But there seems to be still some issue.

**Comment by willu47** [comment]
The tests are failing because no YEAR.csv file is provided in the tests/fixtures/YEAR.csv path.

**Comment by HauHe** [comment]
Ok, interesting, so the check sees that I read in `YEAR.csv` and therefore expects that I have a test including `YEAR.csv`?
Because I didn't write a test including `YEAR.csv`. Do I need to write a corresponding test?

**Comment by HauHe** [comment]
Seems I managed to fix it by adding a YEAR.csv file to tests/fixtures and tests/fixtures/trade

**Review by willu47 — APPROVED** [review]
Looks good @HauHe

**Pull request merged**
